package enums;

public enum EntityActionEnum {

	// ATAQUE
	SOLICITAR_ATAQUE, ATACAR,

	// DEFESA
	DEFENDER,

	// DESVIO
	DESVIAR,

	// ATACADO
	RECEBER_DANO,

	// ATRIBUTO VIDA
	GANHAR_VIDA, PERDER_VIDA,

	// ATRIBUTO VELOCIDADE DE MOVIMENTO
	GANHAR_VELOCIDADE_MOVIMENTO, PERDER_VELOCIDADE_MOVIMENTO,

	// ATRIBUTO ATAQUE
	GANHAR_ATAQUE, PERDER_ATAQUE,

	// ATRIBUTO DEFESA
	GANHAR_DEFESA, PERDER_DEFESA,

	// ATRIBUTO CHANCE DE ACERTO
	GANHAR_CHANCE_ACERTO, PERDER_CHANCE_ACERTO,

	// ATRIBUTO VIDA MÁXIMA
	ALTERAR_VIDA_MAX;

}
